print(30<25)
print(5 < 9)
print(50 > 100)
print()
print()
print(type(5 < 9))
print(type(50 > 100))
print(type(True))
print(type(False))
print(type("Holis"))
print(type(34))
print()
print()
print(True and False)
print(False and True)
print(True or False)
print(False or True)